### ISSUE TITLE
Incompatible with sodium 0.3.0 on 1.17

### ISSUE THREAD

**Issue by Hendrix-Shen** [plusls/oh-my-minecraft-client#10]
The log of this problem is as follows
<pre>
[22:16:30] [Render thread/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/buffers/ChunkModelBuffers (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/buffers/ChunkModelBuffers)
[22:16:30] [Render thread/FATAL]: Mixin apply failed ommc.mixins.json:feature.worldEaterMineHelper.sodium.MixinBlockRenderer -> me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> ommc.mixins.json:feature.worldEaterMineHelper.sodium.MixinBlockRenderer -> Apply Methods -> (Lnet/minecraft/class_1920;Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Lnet/minecraft/class_1087;Lme/jellysquid/mods/sodium/client/render/chunk/compile/buffers/ChunkModelBuffers;ZJLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V:handler$bee000$initRenderContext -> Transform LVT -> var=buffers -> desc=Lme/jellysquid/mods/sodium/client/render/chunk/compile/buffers/ChunkModelBuffers;]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> ommc.mixins.json:feature.worldEaterMineHelper.sodium.MixinBlockRenderer -> Apply Methods -> (Lnet/minecraft/class_1920;Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Lnet/minecraft/class_1087;Lme/jellysquid/mods/sodium/client/render/chunk/compile/buffers/ChunkModelBuffers;ZJLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V:handler$bee000$initRenderContext -> Transform LVT -> var=buffers -> desc=Lme/jellysquid/mods/sodium/client/render/chunk/compile/buffers/ChunkModelBuffers;]
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.10) ~[?:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:490) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:523) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:509) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:381) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.3.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderCacheShared.<init>(ChunkRenderCacheShared.java:28) ~[sodium-fabric-mc1.17-0.3.0+build.428.jar:?]
	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderCacheShared.createRenderContext(ChunkRenderCacheShared.java:60) ~[sodium-fabric-mc1.17-0.3.0+build.428.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.loadWorld(SodiumWorldRenderer.java:109) ~[sodium-fabric-mc1.17-0.3.0+build.428.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setWorld(SodiumWorldRenderer.java:102) ~[sodium-fabric-mc1.17-0.3.0+build.428.jar:?]
	at net.minecraft.client.render.WorldRenderer.handler$zzk000$onWorldChanged(WorldRenderer:4286) ~[?:?]
	at net.minecraft.client.render.WorldRenderer.setWorld(WorldRenderer:737) ~[?:?]
	at net.minecraft.client.MinecraftClient.setWorld(MinecraftClient:2245) ~[?:?]
	at net.minecraft.client.MinecraftClient.joinWorld(MinecraftClient:2169) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onGameJoin(ClientPlayNetworkHandler:364) ~[?:?]
	at net.minecraft.network.packet.s2c.play.GameJoinS2CPacket.apply(GameJoinS2CPacket:100) ~[?:?]
	at net.minecraft.network.packet.s2c.play.GameJoinS2CPacket.apply(GameJoinS2CPacket:18) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1077) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:730) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-1.17-Fabric%200.11.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: me.jellysquid.mods.sodium.client.render.chunk.compile.buffers.ChunkModelBuffers
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:949) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:909) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformLVT(MixinTargetContext.java:543) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:449) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	... 39 more
</pre>

**Comment by Hendrix-Shen** [comment]
I' m sorry about that.
This is a duplicate commit bug.
