### ISSUE TITLE
[1.19.1] OMMC fails to find Magiclib (0.5.33, 1.19.1)

### ISSUE THREAD

**Issue by Notoriousi** [plusls/oh-my-minecraft-client#50]
OMMC throws up the following error whilst having Magiclib 0.5.33 installed:
A potential solution has been determined:
Install magiclib-1_19, version 0.5.30 or later.
Unmet dependency listing:
<html>Mod 'Oh My Minecraft Client for 1.19' (ommc-1_19) 0.5 requires version 0.5.30 or later of magiclib-1_19, which is<br>missing!</html>

After I removed the requirement for it, it still fails to find it:
ModResolutionException: Mod discovery failed!
<html>at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:146)<br>at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)<br>at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:146)<br>at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:210)<br>at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)<br>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)<br>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)<br>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)<br>at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)<br>at java.base/java.lang.reflect.Method.invoke(Method.java:577)<br>at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)<br>at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)<br>at org.multimc.EntryPoint.listen(EntryPoint.java:143)<br>at org.multimc.EntryPoint.main(EntryPoint.java:34)</html>
<html>ParseMetadataException: Error reading fabric.mod.json file for mod at<br>C:\Games\MultiMC\instances\Main\.minecraft\mods\oh-my-minecraft-client-1.19-0.5.jar:<br>net.fabricmc.loader.impl.lib.gson.MalformedJsonException: Expected name at line 36 column 4 path $.depends.minecraft</html>
<html>at net.fabricmc.loader.impl.metadata.ModMetadataParser.parseMetadata(ModMetadataParser.java:57)<br>at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.parseMetadata(ModDiscoverer.java:465)<br>at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:287)<br>at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:250)<br>at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212)<br>at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)<br>at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)<br>at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)<br>at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)<br>at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)<br>at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)</html>
MalformedJsonException: Expected name at line 36 column 4 path $.depends.minecraft
<html>at net.fabricmc.loader.impl.lib.gson.JsonReader.syntaxError(JsonReader.java:1570)<br>at net.fabricmc.loader.impl.lib.gson.JsonReader.doPeek(JsonReader.java:505)<br>at net.fabricmc.loader.impl.lib.gson.JsonReader.hasNext(JsonReader.java:414)<br>at net.fabricmc.loader.impl.metadata.V1ModMetadataParser.readDependenciesContainer(V1ModMetadataParser.java:443)<br>at net.fabricmc.loader.impl.metadata.V1ModMetadataParser.parse(V1ModMetadataParser.java:151)<br>at net.fabricmc.loader.impl.metadata.ModMetadataParser.readModMetadata(ModMetadataParser.java:142)<br>at net.fabricmc.loader.impl.metadata.ModMetadataParser.readModMetadata(ModMetadataParser.java:105)<br>at net.fabricmc.loader.impl.metadata.ModMetadataParser.parseMetadata(ModMetadataParser.java:45)<br>... 10 more</html>

**Comment by Notoriousi** [comment]
Update: Magiclib 0.5.34 did not fix this

**Comment by bAdOoWindy** [comment]
fails to find Magiclib (0.5.37, 1.19.2)

**Comment by Hendrix-Shen** [comment]
See https://github.com/Hendrix-Shen/MagicLib/issues/7.
