### ISSUE TITLE
1.19.3 无法识别magiclib?

### ISSUE THREAD

**Issue by Realzhazha** [plusls/oh-my-minecraft-client#75]
[19:05:07] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.17
[19:05:07] [main/WARN]: Mod resolution failed
[19:05:07] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE ommc-1_19 0.5 {depends magiclib-1_19 @ [>=0.5.30]}, ROOT_FORCELOAD_SINGLE ommc-1_19 0.5]
[19:05:07] [main/INFO]: Reason: [HARD_DEP ommc-1_19 0.5 {depends magiclib-1_19 @ [>=0.5.30]}, HARD_DEP magiclib-1_14_4 0.7.293+17aa28c-stable {depends minecraft @ [1.14.x]}, HARD_DEP magiclib-1_15_2 0.7.293+17aa28c-stable {depends minecraft @ [1.15.x]}, HARD_DEP magiclib-1_16_5 0.7.293+17aa28c-stable {depends minecraft @ [1.16.x]}, HARD_DEP magiclib-1_17_1 0.7.293+17aa28c-stable {depends minecraft @ [1.17.x]}, HARD_DEP magiclib-1_18_2 0.7.293+17aa28c-stable {depends minecraft @ [1.18.x]}, HARD_DEP magiclib-1_19_2 0.7.293+17aa28c-stable {depends minecraft @ [>1.18.2 <=1.19.2]}, HARD_DEP magiclib-1_19_4 0.7.293+17aa28c-stable {depends minecraft @ [1.19.4]}]
[19:05:07] [main/INFO]: Fix: add [add:magiclib-1_19 0.5.30 ([[0.5.30,∞)])], remove [], replace []
[19:05:07] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install magiclib-1_19, version 0.5.30 or later.
Unmet dependency listing:
	 - Mod 'Oh My Minecraft Client for 1.19' (ommc-1_19) 0.5 requires version 0.5.30 or later of magiclib-1_19, which is missing!
	 - Mod 'MagicLib for 1.14.4' (magiclib-1_14_4) 0.7.293+17aa28c-stable requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'MagicLib for 1.15.2' (magiclib-1_15_2) 0.7.293+17aa28c-stable requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'MagicLib for 1.16.5' (magiclib-1_16_5) 0.7.293+17aa28c-stable requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'MagicLib for 1.17.1' (magiclib-1_17_1) 0.7.293+17aa28c-stable requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'MagicLib for 1.18.2' (magiclib-1_18_2) 0.7.293+17aa28c-stable requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'MagicLib for 1.19.2' (magiclib-1_19_2) 0.7.293+17aa28c-stable requires any version between 1.18.2 (exclusive) and 1.19.2 (inclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'MagicLib for 1.19.4' (magiclib-1_19_4) 0.7.293+17aa28c-stable requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]

报错信息如上
似乎是已经安装了magiclib，但是无法识别到？
game: 1.19.3
mods: OMMC 0.5, fabric 0.14.17, magiclib 0.7.293 17aa28c fabric api 0.75.1

**Comment by Hendrix-Shen** [comment]
尝试此版本 [0.5.269+957c0dd](https://github.com/Nyan-Work/oh-my-minecraft-client/releases/tag/nyan-work%2Fdev.12)。
