### ISSUE TITLE
0.5 版本无法使用o+c打开设置界面，也无法使用mod menu内打开设置界面

### ISSUE THREAD

**Issue by Sober7135** [plusls/oh-my-minecraft-client#82]
Minecraft version 1.20.1
magiclib-all-0.7.346+e235d92-stable.jar
malilib-fabric-1.20.1-0.16.1.jar
fabric-api-0.86.1+1.20.1.jar
看了一下日志，应该是这个炸了（？）
```
[22:46:03] [Render thread/ERROR]: Mod ommc provides a broken implementation of ModMenuApi
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'modmenu' provided by 'ommc'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.14.21.jar:?]
	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$1(ModMenu.java:74) ~[modmenu-7.2.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:70) ~[modmenu-7.2.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[1201.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: com.plusls.ommc.compat.modmenu.WrapperModMenuApiImpl
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
	... 11 more
Caused by: java.lang.ClassNotFoundException: com.plusls.ommc.compat.modmenu.WrapperModMenuApiImpl
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
	... 11 more

```

**Comment by liqwang** [comment]
0.5版本只支持到1.19：https://modrinth.com/mod/oh-my-minecraft-client/version/0.5
项目目前在这个仓库维护，里面的beta版支持到了1.20.1
https://github.com/Nyan-Work/oh-my-minecraft-client/releases
